apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.containerName }}
    chart: {{ $.Chart.Name }}
data:
  ca.pub: |
{{ required "A valid .Values.conf.CAPublicKey entry required!" .Values.config.CAPublicKey | indent 4 }}

{{- if .Values.config.sessionTermination.enabled }}
  api-url: |

  api-token: |

{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.containerName }}
    chart: {{ $.Chart.Name }}
data:
{{- if .Values.config.logForwording.enabled }}
  logand.conf: |
{{ required "A valid .Values.config.logForwording.logand entry required!" .Values.config.logForwording.settings | indent 4 }}
{{- end }}

{{- if .Values.config.akeylessConfigFile }}
  akeyless_config_file: |
{{ .Values.config.akeylessConfigFile | indent 4 }}
{{- end }}