# Default values for akeyless-services.

replicaCount: 2

image:
  repository: akeyless/base
  pullPolicy: IfNotPresent
  tag: latest

containerName: "api-gateway"

service:
  # Remove the {} and add any needed annotations regarding your LoadBalancer implementation
  annotations: {}
  type: LoadBalancer
  ports:
    - name: web-ui
      port: 18888
      protocol: TCP
    - name: configure-app
      port: 8000
      protocol: TCP
    - name: curl-proxy
      port: 8080
      protocol: TCP
    - name: hvp
      port: 8200
      protocol: TCP

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 120 # Startup can take time
  periodSeconds: 10
  timeoutSeconds: 5

# Akeyless requires data persistence to be shared within all pods in the cluster
# Currently only ReadWriteMany is supported
# accessMode: ReadWriteMany (AWS)
# accessMode: ReadWriteOnce + ReadOnlyMany (GCP)
# Change the below values according to your environment except for the hostPath values
persistence:
  volumes: {}
#    - name: akeyless-conf
#      storageClassName: efs-sc
#      storageClassDriver: efs.csi.aws.com
#      size: 2Gi
#      mountPath: /var/akeyless
#      fsId: "fs-123abc45"
#    - name: akeyless-profiles
#      storageClassName: efs-sc
#      storageClassDriver: efs.csi.aws.com
#      size: 2Gi
#      mountPath: /root/.akeyless
#      fsId: "fs-678def90"

# AWS
  accessModes:
  - ReadWriteMany

# GCP
#  accessModes:
#  - ReadWriteOnce
#  - ReadOnlyMany

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env: {}
  # Any environment variables needed

HPA:
  # Set the below to false in case you do not want to add Horizontal Pod AutoScaling to the StatefulSet (not recommended)
  # Note that metrics server must be installed for this to work:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: false
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50
