apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "akeyless-services.fullname" . }}
  labels:
    {{- include "akeyless-services.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "akeyless-services.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "akeyless-services.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "akeyless-services.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- range .Values.persistence.volumes }}
      - name: {{ .name | title | lower }}
        persistentVolumeClaim:
          claimName: {{ printf "%s-%s" $.Release.Name .name | title | lower }}
      {{- end }}
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /status
              port: 18888
{{- toYaml .Values.livenessProbe | trim | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /status
              port: 18888
{{- toYaml .Values.readinessProbe | trim | nindent 12 }}
          volumeMounts:
          {{- range .Values.persistence.volumes }}
            - name: {{ .name | title | lower }}
              mountPath: {{ .mountPath | quote }}
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.akeylessUserAuth.adminAccessId }}
            - name: ADMIN_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-conf-secret
                  key: ADMIN_ACCESS_ID
          {{- end }}
          {{- if .Values.akeylessUserAuth.adminAccessKey }}
            - name: ADMIN_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-conf-secret
                  key: ADMIN_ACCESS_KEY
          {{- end }}
          {{- if .Values.akeylessUserAuth.adminPassword }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-conf-secret
                  key: ADMIN_PASSWORD
          {{- end }}
            - name: CLUSTER_NAME
              value: {{ .Values.akeylessUserAuth.clusterName }}
            - name: CONFIG_PROTECTION_KEY_NAME
              value: {{ .Values.akeylessUserAuth.configProtectionKeyName }}
          {{- if .Values.env }}
  {{- toYaml .Values.env | nindent 12 }}
          {{- end }}